name: GraalVM build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '22'      # See 'Options' for more details
          distribution: 'graalvm' # See 'Supported distributions' for available options
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Example step
        run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          java --version
          native-image --version
      - name: Extract configuration files
        run: cd MtdrSpring;
              wget https://objectstorage.mx-queretaro-1.oraclecloud.com/p/Bg_eV5KPa4E0iFKeKlQ_k55F3OcfCs_33dNFyE2Gz9SBIqKaoFRf_JkaeHF3andL/n/axzmghqes1gn/b/reacttodo-rolax/o/deployment_config.tgz ;
              tar -xzvf deployment_config.tgz;
              source env.sh;
              echo "${{ secrets.AUTH_TOKEN }}" | docker login -u "axzmghqes1gn/adan.ruiz@tec.mx" --password-stdin mx-queretaro-1.ocir.io ;
      - name: "Build"
        run:  cd MtdrSpring;
              source env.sh;
              (cd backend;source build.sh)
